#!/usr/bin/env bash
# Toggle proxy settings for a remote Linux server using an SSH reverse tunnel.
# Intended usage from repository root:
#   source ./proxyctl.sh on
#   source ./proxyctl.sh off
#   bash ./proxyctl.sh status

PROXY_HOST="${PROXY_HOST:-127.0.0.1}"
PROXY_PORT="${PROXY_PORT:-17890}"
HTTP_PROXY_URL="${HTTP_PROXY_URL:-http://${PROXY_HOST}:${PROXY_PORT}}"
HTTPS_PROXY_URL="${HTTPS_PROXY_URL:-http://${PROXY_HOST}:${PROXY_PORT}}"
ALL_PROXY_URL="${ALL_PROXY_URL:-socks5h://${PROXY_HOST}:${PROXY_PORT}}"
PROXY_ENV_FILE="${PROXY_ENV_FILE:-$HOME/.proxy_env}"
GIT_HTTP_VERSION="${GIT_HTTP_VERSION:-HTTP/1.1}"

proxyctl_is_sourced() {
    [[ "${BASH_SOURCE[0]}" != "$0" ]]
}

proxyctl_usage() {
    cat <<USAGE
Usage:
  source ./proxyctl.sh on
  source ./proxyctl.sh off
  bash ./proxyctl.sh status
  bash ./proxyctl.sh run <command...>
  bash ./proxyctl.sh print

Commands:
  on      Set current-shell proxy variables, write ~/.proxy_env, and configure Git globally.
  off     Clear current-shell proxy variables, remove ~/.proxy_env, and clear Git proxy config.
  status  Show environment, Git config, reverse-tunnel listener, and GitHub connectivity.
  run     Run one command with proxy environment variables.
  print   Print shell export commands.

Defaults:
  HTTP/HTTPS proxy: $HTTP_PROXY_URL
  ALL proxy:        $ALL_PROXY_URL
USAGE
}

proxyctl_print_exports() {
    cat <<ENVEOF
export http_proxy="$HTTP_PROXY_URL"
export https_proxy="$HTTPS_PROXY_URL"
export all_proxy="$ALL_PROXY_URL"
export HTTP_PROXY="$HTTP_PROXY_URL"
export HTTPS_PROXY="$HTTPS_PROXY_URL"
export ALL_PROXY="$ALL_PROXY_URL"
export no_proxy="localhost,127.0.0.1,::1"
export NO_PROXY="localhost,127.0.0.1,::1"
ENVEOF
}

proxyctl_apply_env() {
    export http_proxy="$HTTP_PROXY_URL"
    export https_proxy="$HTTPS_PROXY_URL"
    export all_proxy="$ALL_PROXY_URL"
    export HTTP_PROXY="$HTTP_PROXY_URL"
    export HTTPS_PROXY="$HTTPS_PROXY_URL"
    export ALL_PROXY="$ALL_PROXY_URL"
    export no_proxy="localhost,127.0.0.1,::1"
    export NO_PROXY="localhost,127.0.0.1,::1"
}

proxyctl_clear_env() {
    unset http_proxy https_proxy all_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY no_proxy NO_PROXY 2>/dev/null || true
}

proxyctl_write_env_file() {
    {
        echo '# Generated by proxyctl.sh'
        proxyctl_print_exports
    } > "$PROXY_ENV_FILE"
    chmod 600 "$PROXY_ENV_FILE"
}

proxyctl_git_on() {
    command -v git >/dev/null 2>&1 || {
        echo '[WARN] git is not installed; skipped Git proxy configuration.' >&2
        return 0
    }

    git config --global --replace-all http.proxy "$HTTP_PROXY_URL"
    git config --global --replace-all https.proxy "$HTTPS_PROXY_URL"
    git config --global --replace-all http.version "$GIT_HTTP_VERSION"

    local actual_http actual_https
    actual_http="$(git config --global --get http.proxy 2>/dev/null || true)"
    actual_https="$(git config --global --get https.proxy 2>/dev/null || true)"
    if [[ "$actual_http" != "$HTTP_PROXY_URL" || "$actual_https" != "$HTTPS_PROXY_URL" ]]; then
        echo '[ERROR] Git proxy configuration verification failed.' >&2
        echo "        expected http.proxy=$HTTP_PROXY_URL" >&2
        echo "        actual   http.proxy=${actual_http:-<unset>}" >&2
        echo "        expected https.proxy=$HTTPS_PROXY_URL" >&2
        echo "        actual   https.proxy=${actual_https:-<unset>}" >&2
        return 1
    fi
}

proxyctl_git_off() {
    command -v git >/dev/null 2>&1 || return 0
    git config --global --unset-all http.proxy 2>/dev/null || true
    git config --global --unset-all https.proxy 2>/dev/null || true
}

proxyctl_port_check() {
    if command -v ss >/dev/null 2>&1; then
        ss -ltnp 2>/dev/null | grep -E "[:.]${PROXY_PORT}[[:space:]]"
    elif command -v netstat >/dev/null 2>&1; then
        netstat -ltnp 2>/dev/null | grep -E "[:.]${PROXY_PORT}[[:space:]]"
    else
        return 2
    fi
}

proxyctl_curl_test() {
    command -v curl >/dev/null 2>&1 || return 2
    curl -I --max-time 15 --proxy "$HTTP_PROXY_URL" https://github.com 2>/dev/null | head -n 1
}

proxyctl_git_test() {
    command -v git >/dev/null 2>&1 || return 2
    git ls-remote https://github.com/GGBOND121382/stock_realtime_v021_full.git HEAD 2>/dev/null | head -n 1
}

proxyctl_on() {
    proxyctl_apply_env
    proxyctl_write_env_file
    proxyctl_git_on || return 1

    echo '[OK] proxy enabled'
    echo "     http_proxy=$HTTP_PROXY_URL"
    echo "     https_proxy=$HTTPS_PROXY_URL"
    echo "     all_proxy=$ALL_PROXY_URL"
    echo "     git http.proxy=$(git config --global --get http.proxy 2>/dev/null || echo '<unavailable>')"
    echo "     git https.proxy=$(git config --global --get https.proxy 2>/dev/null || echo '<unavailable>')"
    echo "     env file=$PROXY_ENV_FILE"

    if ! proxyctl_port_check >/dev/null 2>&1; then
        echo "[WARN] No listener detected on ${PROXY_HOST}:${PROXY_PORT}." >&2
        echo '       Check the SSH RemoteForward and local Clash process.' >&2
    fi
}

proxyctl_off() {
    proxyctl_clear_env
    rm -f "$PROXY_ENV_FILE"
    proxyctl_git_off
    echo '[OK] proxy disabled'
    echo "     removed env file: $PROXY_ENV_FILE"
    echo '     removed Git global http.proxy / https.proxy'
}

proxyctl_status() {
    echo '========== environment =========='
    env | grep -Ei '^(http_proxy|https_proxy|all_proxy|HTTP_PROXY|HTTPS_PROXY|ALL_PROXY|no_proxy|NO_PROXY)=' || echo 'no proxy environment variables found'

    echo
    echo '========== Git global config =========='
    if command -v git >/dev/null 2>&1; then
        git config --global --get-regexp '^(http|https)\.proxy|^http\.version' 2>/dev/null || echo 'no matching Git global proxy config found'
    else
        echo 'git not installed'
    fi

    echo
    echo '========== reverse-tunnel listener =========='
    proxyctl_port_check || echo "no listener found on ${PROXY_HOST}:${PROXY_PORT}"

    echo
    echo '========== curl through explicit HTTP proxy =========='
    proxyctl_curl_test || echo 'curl test failed'

    echo
    echo '========== GitHub Git test =========='
    proxyctl_git_test || echo 'git ls-remote test failed'
}

proxyctl_run() {
    [[ "$#" -gt 0 ]] || {
        echo "[ERROR] Missing command after 'run'." >&2
        return 1
    }
    http_proxy="$HTTP_PROXY_URL" \
    https_proxy="$HTTPS_PROXY_URL" \
    all_proxy="$ALL_PROXY_URL" \
    HTTP_PROXY="$HTTP_PROXY_URL" \
    HTTPS_PROXY="$HTTPS_PROXY_URL" \
    ALL_PROXY="$ALL_PROXY_URL" \
    no_proxy="localhost,127.0.0.1,::1" \
    NO_PROXY="localhost,127.0.0.1,::1" \
    "$@"
}

proxyctl_cmd="${1:-}"
case "$proxyctl_cmd" in
    on) proxyctl_on ;;
    off) proxyctl_off ;;
    status) proxyctl_status ;;
    run) shift; proxyctl_run "$@" ;;
    print) proxyctl_print_exports ;;
    help|-h|--help|'') proxyctl_usage ;;
    *)
        echo "[ERROR] Unknown command: $proxyctl_cmd" >&2
        proxyctl_usage
        if proxyctl_is_sourced; then return 1; else exit 1; fi
        ;;
esac
