#!/usr/bin/env bash
# proxyctl.sh
#
# Purpose:
#   Toggle proxy settings on a remote Linux server that uses an SSH reverse tunnel.
#
# Default proxy endpoint on the remote server:
#   http_proxy / https_proxy -> http://127.0.0.1:17890
#   all_proxy                -> socks5h://127.0.0.1:17890
#
# Typical tunnel from local machine:
#   RemoteForward 17890 127.0.0.1:7890
#
# Usage:
#   source ./proxyctl.sh on
#   source ./proxyctl.sh off
#   ./proxyctl.sh status
#   ./proxyctl.sh run <command...>
#
# Notes:
#   1. Use "source ./proxyctl.sh on/off" if you want to modify the current shell.
#   2. Direct execution cannot export/unset variables in the parent shell.
#   3. This script does NOT create the SSH tunnel. It only configures the remote server to use it.

set -u

PROXY_HOST="${PROXY_HOST:-127.0.0.1}"
PROXY_PORT="${PROXY_PORT:-17890}"

HTTP_PROXY_URL="${HTTP_PROXY_URL:-http://${PROXY_HOST}:${PROXY_PORT}}"
HTTPS_PROXY_URL="${HTTPS_PROXY_URL:-http://${PROXY_HOST}:${PROXY_PORT}}"
ALL_PROXY_URL="${ALL_PROXY_URL:-socks5h://${PROXY_HOST}:${PROXY_PORT}}"

PROXY_ENV_FILE="${PROXY_ENV_FILE:-$HOME/.proxy_env}"
GIT_HTTP_VERSION="${GIT_HTTP_VERSION:-HTTP/1.1}"

is_sourced() {
    [ "${BASH_SOURCE[0]}" != "$0" ]
}

print_usage() {
    cat <<USAGE
Usage:
  source ./proxyctl.sh on
  source ./proxyctl.sh off
  ./proxyctl.sh status
  ./proxyctl.sh run <command...>
  ./proxyctl.sh print

Commands:
  on      Enable proxy environment variables for the current shell if sourced,
          write \$HOME/.proxy_env, and set Git global proxy.
  off     Disable proxy environment variables for the current shell if sourced,
          remove \$HOME/.proxy_env, and unset Git global proxy.
  status  Show current proxy environment, Git proxy config, port listener, and curl test.
  run     Run one command with proxy environment variables.
  print   Print shell export commands without changing anything.

Default:
  PROXY_HOST=$PROXY_HOST
  PROXY_PORT=$PROXY_PORT
  HTTP_PROXY_URL=$HTTP_PROXY_URL
  HTTPS_PROXY_URL=$HTTPS_PROXY_URL
  ALL_PROXY_URL=$ALL_PROXY_URL
  PROXY_ENV_FILE=$PROXY_ENV_FILE

Examples:
  source ./proxyctl.sh on
  source ./proxyctl.sh off
  ./proxyctl.sh status
  ./proxyctl.sh run git pull origin master
  PROXY_PORT=17891 source ./proxyctl.sh on
USAGE
}

write_proxy_env_file() {
    cat > "$PROXY_ENV_FILE" <<ENVEOF
# Generated by proxyctl.sh
# Source this file manually if needed:
#   source "$PROXY_ENV_FILE"
export http_proxy="$HTTP_PROXY_URL"
export https_proxy="$HTTPS_PROXY_URL"
export all_proxy="$ALL_PROXY_URL"
export HTTP_PROXY="$HTTP_PROXY_URL"
export HTTPS_PROXY="$HTTPS_PROXY_URL"
export ALL_PROXY="$ALL_PROXY_URL"
export no_proxy="localhost,127.0.0.1,::1"
export NO_PROXY="localhost,127.0.0.1,::1"
ENVEOF
    chmod 600 "$PROXY_ENV_FILE"
}

print_exports() {
    cat <<ENVEOF
export http_proxy="$HTTP_PROXY_URL"
export https_proxy="$HTTPS_PROXY_URL"
export all_proxy="$ALL_PROXY_URL"
export HTTP_PROXY="$HTTP_PROXY_URL"
export HTTPS_PROXY="$HTTPS_PROXY_URL"
export ALL_PROXY="$ALL_PROXY_URL"
export no_proxy="localhost,127.0.0.1,::1"
export NO_PROXY="localhost,127.0.0.1,::1"
ENVEOF
}

apply_env_current_shell() {
    export http_proxy="$HTTP_PROXY_URL"
    export https_proxy="$HTTPS_PROXY_URL"
    export all_proxy="$ALL_PROXY_URL"

    export HTTP_PROXY="$HTTP_PROXY_URL"
    export HTTPS_PROXY="$HTTPS_PROXY_URL"
    export ALL_PROXY="$ALL_PROXY_URL"

    export no_proxy="localhost,127.0.0.1,::1"
    export NO_PROXY="localhost,127.0.0.1,::1"
}

unset_env_current_shell() {
    unset http_proxy || true
    unset https_proxy || true
    unset all_proxy || true
    unset HTTP_PROXY || true
    unset HTTPS_PROXY || true
    unset ALL_PROXY || true
    unset no_proxy || true
    unset NO_PROXY || true
}

git_proxy_on() {
    if command -v git >/dev/null 2>&1; then
        git config --global http.proxy "$HTTP_PROXY_URL"
        git config --global https.proxy "$HTTPS_PROXY_URL"
        git config --global http.version "$GIT_HTTP_VERSION"
    fi
}

git_proxy_off() {
    if command -v git >/dev/null 2>&1; then
        git config --global --unset http.proxy 2>/dev/null || true
        git config --global --unset https.proxy 2>/dev/null || true
        # Keep http.version because HTTP/1.1 is often safer through proxies.
        # Uncomment the next line if you also want to remove it.
        # git config --global --unset http.version 2>/dev/null || true
    fi
}

port_check() {
    if command -v ss >/dev/null 2>&1; then
        ss -ltnp 2>/dev/null | grep -E "[:.]${PROXY_PORT}[[:space:]]" || return 1
    elif command -v netstat >/dev/null 2>&1; then
        netstat -ltnp 2>/dev/null | grep -E "[:.]${PROXY_PORT}[[:space:]]" || return 1
    else
        return 2
    fi
}

curl_test() {
    if ! command -v curl >/dev/null 2>&1; then
        echo "curl not installed"
        return 2
    fi

    curl -I --max-time 15 -x "$HTTP_PROXY_URL" https://github.com 2>/dev/null | head -n 1
}

proxy_on() {
    apply_env_current_shell
    write_proxy_env_file
    git_proxy_on

    echo "[OK] proxy enabled"
    echo "     http_proxy=$HTTP_PROXY_URL"
    echo "     https_proxy=$HTTPS_PROXY_URL"
    echo "     all_proxy=$ALL_PROXY_URL"
    echo "     env file=$PROXY_ENV_FILE"

    if ! port_check >/dev/null 2>&1; then
        echo "[WARN] No listener detected on ${PROXY_HOST}:${PROXY_PORT}."
        echo "       Check whether VS Code/SSH RemoteForward is connected."
    fi
}

proxy_off() {
    unset_env_current_shell
    rm -f "$PROXY_ENV_FILE"
    git_proxy_off

    echo "[OK] proxy disabled"
    echo "     removed env file: $PROXY_ENV_FILE"
    echo "     removed Git global http.proxy / https.proxy"
}

proxy_status() {
    echo "========== environment =========="
    env | grep -Ei '^(http_proxy|https_proxy|all_proxy|HTTP_PROXY|HTTPS_PROXY|ALL_PROXY|no_proxy|NO_PROXY)=' || echo "no proxy environment variables found"

    echo
    echo "========== env file =========="
    if [ -f "$PROXY_ENV_FILE" ]; then
        echo "$PROXY_ENV_FILE exists"
        sed -n '1,20p' "$PROXY_ENV_FILE"
    else
        echo "$PROXY_ENV_FILE not found"
    fi

    echo
    echo "========== git config =========="
    if command -v git >/dev/null 2>&1; then
        git config --global --get-regexp '^(http|https)\.proxy|^http\.version' 2>/dev/null || echo "no matching Git global proxy config found"
    else
        echo "git not installed"
    fi

    echo
    echo "========== port check =========="
    if port_check; then
        :
    else
        rc=$?
        if [ "$rc" -eq 2 ]; then
            echo "neither ss nor netstat is available"
        else
            echo "no listener found on ${PROXY_HOST}:${PROXY_PORT}"
        fi
    fi

    echo
    echo "========== curl test =========="
    test_result="$(curl_test || true)"
    if [ -n "$test_result" ]; then
        echo "$test_result"
    else
        echo "curl test failed"
    fi
}

proxy_run() {
    if [ "$#" -eq 0 ]; then
        echo "[ERROR] Missing command after 'run'."
        echo "Example: ./proxyctl.sh run git pull origin master"
        return 1
    fi

    http_proxy="$HTTP_PROXY_URL" \
    https_proxy="$HTTPS_PROXY_URL" \
    all_proxy="$ALL_PROXY_URL" \
    HTTP_PROXY="$HTTP_PROXY_URL" \
    HTTPS_PROXY="$HTTPS_PROXY_URL" \
    ALL_PROXY="$ALL_PROXY_URL" \
    no_proxy="localhost,127.0.0.1,::1" \
    NO_PROXY="localhost,127.0.0.1,::1" \
    "$@"
}

cmd="${1:-}"

case "$cmd" in
    on)
        proxy_on
        if ! is_sourced; then
            echo
            echo "[WARN] You executed the script directly."
            echo "       Environment variables were set only inside this script process."
            echo "       Use this instead when you need the current shell to keep them:"
            echo "       source ./proxyctl.sh on"
            echo
            echo "       Git config and $PROXY_ENV_FILE have already been written."
        fi
        ;;
    off)
        proxy_off
        if ! is_sourced; then
            echo
            echo "[WARN] You executed the script directly."
            echo "       Existing proxy variables in the parent shell cannot be unset by a child process."
            echo "       Use this instead when you need the current shell to clear them:"
            echo "       source ./proxyctl.sh off"
            echo
            echo "       Git config and $PROXY_ENV_FILE have already been cleaned."
        fi
        ;;
    status)
        proxy_status
        ;;
    run)
        shift
        proxy_run "$@"
        ;;
    print)
        print_exports
        ;;
    -h|--help|help|"")
        print_usage
        ;;
    *)
        echo "[ERROR] Unknown command: $cmd"
        echo
        print_usage
        if is_sourced; then
            return 1
        else
            exit 1
        fi
        ;;
esac
