#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

from pathlib import Path


def replace_once(txt: str, old: str, new: str, label: str) -> tuple[str, bool]:
    if old not in txt:
        print(f"[WARN] marker not found: {label}")
        return txt, False
    return txt.replace(old, new, 1), True


def patch_backtest() -> None:
    path = Path("portfolio_decision/backtest_historical_score_portfolio.py")
    if not path.exists():
        print(f"[SKIP] {path}")
        return
    txt = path.read_text(encoding="utf-8")
    old_txt = txt

    import_marker = '''if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))


DEFAULT_EVAL_CONFIG = {
'''
    import_add = '''if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

from model_training.optimize_nextday_vwap_model import add_trade_returns


DEFAULT_EVAL_CONFIG = {
'''
    if "from model_training.optimize_nextday_vwap_model import add_trade_returns" not in txt:
        txt, _ = replace_once(txt, import_marker, import_add, "backtest import add_trade_returns")

    load_marker = '''        samples = samples.dropna(subset=["date"]).sort_values("date")

        cols = read_feature_columns(artifact_dir)
'''
    load_add = '''        samples = samples.dropna(subset=["date"]).sort_values("date")

        # Keep historical scoring and settlement on the exact same trade-return
        # semantics as model_training/search_walk_forward_model_complexity.py.
        # Raw training_samples*.csv files may not store trade_net_close_return /
        # trade_target_or_close_return; these are generated by add_trade_returns.
        samples = add_trade_returns(
            samples,
            cost_bps=as_float(meta.get("round_trip_cost_bps"), 1.7),
            target_bps=as_float(meta.get("target_hit_bps"), 50.0),
            entry_policy=str(meta.get("entry_policy") or "vwap_low"),
            entry_vwap_premium_bps=as_float(meta.get("entry_vwap_premium_bps"), 50.0),
        )

        cols = read_feature_columns(artifact_dir)
'''
    if "Raw training_samples*.csv files may not store trade_net_close_return" not in txt:
        txt, _ = replace_once(txt, load_marker, load_add, "backtest add_trade_returns on samples")

    dataclass_marker = '''    ev_bps: float
    utility_bps: float
'''
    dataclass_add = '''    ev_bps: float
    utility_bps: float
    entry_policy: str = ""
    label_mode: str = ""
    expected_return_col: str = ""
    samples: str = ""
    metadata_path: str = ""
'''
    if "expected_return_col: str = \"\"" not in txt:
        txt = txt.replace(dataclass_marker, dataclass_add, 2)

    openlot_marker = '''                    utility_bps=as_float(r.get("utility_bps", np.nan), np.nan),
                ))
'''
    openlot_add = '''                    utility_bps=as_float(r.get("utility_bps", np.nan), np.nan),
                    entry_policy=str(r.get("entry_policy", "")),
                    label_mode=str(r.get("label_mode", "")),
                    expected_return_col=str(r.get("expected_return_col", "")),
                    samples=str(r.get("samples", "")),
                    metadata_path=str(r.get("metadata_path", "")),
                ))
'''
    if "expected_return_col=str(r.get(\"expected_return_col\"" not in txt:
        txt, _ = replace_once(txt, openlot_marker, openlot_add, "backtest openlot usage fields")

    scheduled_marker = '''                    utility_bps=lot.utility_bps,
                    exit_reason="scheduled_hold_days",
'''
    scheduled_add = '''                    utility_bps=lot.utility_bps,
                    entry_policy=lot.entry_policy,
                    label_mode=lot.label_mode,
                    expected_return_col=lot.expected_return_col,
                    samples=lot.samples,
                    metadata_path=lot.metadata_path,
                    exit_reason="scheduled_hold_days",
'''
    if "entry_policy=lot.entry_policy" not in txt:
        txt = txt.replace(scheduled_marker, scheduled_add, 1)

    force_marker = '''                utility_bps=lot.utility_bps,
                exit_reason="force_close_at_end",
'''
    force_add = '''                utility_bps=lot.utility_bps,
                entry_policy=lot.entry_policy,
                label_mode=lot.label_mode,
                expected_return_col=lot.expected_return_col,
                samples=lot.samples,
                metadata_path=lot.metadata_path,
                exit_reason="force_close_at_end",
'''
    if txt.count("entry_policy=lot.entry_policy") < 2:
        txt = txt.replace(force_marker, force_add, 1)

    if txt != old_txt:
        path.write_text(txt, encoding="utf-8")
        print(f"[PATCHED] {path}")
    else:
        print(f"[UNCHANGED] {path}")


def patch_adapter() -> None:
    path = Path("portfolio_decision/portfolio_confirm_from_buy_signals.py")
    if not path.exists():
        print(f"[SKIP] {path}")
        return
    txt = path.read_text(encoding="utf-8")
    old_txt = txt

    marker = '        sector = r.get("sector", r.get("industry", "UNKNOWN"))\n\n        sig_rows.append({\n'
    insert = '''        sector = r.get("sector", r.get("industry", "UNKNOWN"))

        entry_policy = str(r.get("entry_policy", meta.get("entry_policy", "")) or "").strip()
        entry_vwap_premium_bps = as_float(
            r.get("entry_vwap_premium_bps", meta.get("entry_vwap_premium_bps", 50.0)),
            50.0,
        )
        samples = str(
            r.get("samples", r.get("sample_file", meta.get("samples", meta.get("sample_file", "")))) or ""
        ).strip()
        expected_return_col = str(r.get("expected_return_col", "") or "").strip()
        if not expected_return_col:
            lm = str(label_mode).lower()
            expected_return_col = "trade_target_or_close_return" if lm.startswith("hit") or lm == "hit" else "trade_net_close_return"

        sig_rows.append({
'''
    if "expected_return_col = str(r.get(\"expected_return_col\"" not in txt:
        txt, _ = replace_once(txt, marker, insert, "adapter entry fields before sig_rows")

    marker = '            "metadata_path": str(meta_path) if meta_path else "",\n        })\n'
    insert = '''            "entry_policy": entry_policy,
            "entry_vwap_premium_bps": entry_vwap_premium_bps,
            "samples": samples,
            "expected_return_col": expected_return_col,
            "metadata_path": str(meta_path) if meta_path else "",
        })
'''
    if '"expected_return_col": expected_return_col' not in txt:
        txt, _ = replace_once(txt, marker, insert, "adapter sig_rows fields")

    marker = '            "entry_policy": meta.get("entry_policy", ""),\n            "sector": sector,\n        })\n'
    insert = '''            "entry_policy": entry_policy,
            "entry_vwap_premium_bps": entry_vwap_premium_bps,
            "samples": samples,
            "expected_return_col": expected_return_col,
            "sector": sector,
        })
'''
    if '"samples": samples' not in txt:
        txt, _ = replace_once(txt, marker, insert, "adapter met_rows fields")

    if txt != old_txt:
        path.write_text(txt, encoding="utf-8")
        print(f"[PATCHED] {path}")
    else:
        print(f"[UNCHANGED] {path}")


def patch_optimizer() -> None:
    path = Path("portfolio_decision/daily_portfolio_confirm_pyscipopt.py")
    if not path.exists():
        print(f"[SKIP] {path}")
        return
    txt = path.read_text(encoding="utf-8")
    old_txt = txt

    marker = '''    fail_loss_bps: float
    ev_bps: float
'''
    insert = '''    fail_loss_bps: float
    entry_policy: str
    entry_vwap_premium_bps: float
    samples: str
    expected_return_col: str
    metadata_path: str
    ev_bps: float
'''
    if "expected_return_col: str" not in txt:
        txt, _ = replace_once(txt, marker, insert, "optimizer candidate dataclass fields")

    marker = '''        target_hit_bps = as_float(get_row_field(row, "target_hit_bps", 80.0 if "80" in label_mode else 50.0), 80.0)
        pred_prob = parse_rate_decimal(get_row_field(row, "pred_prob", get_row_field(row, "win_rate", cfg["default_hit_prob"])), cfg["default_hit_prob"])
'''
    insert = '''        target_hit_bps = as_float(get_row_field(row, "target_hit_bps", 80.0 if "80" in label_mode else 50.0), 80.0)
        entry_policy = str(get_row_field(row, "entry_policy", "") or "")
        entry_vwap_premium_bps = as_float(get_row_field(row, "entry_vwap_premium_bps", 50.0), 50.0)
        samples = str(get_row_field(row, "samples", "") or "")
        expected_return_col = str(get_row_field(row, "expected_return_col", "") or "")
        metadata_path = str(get_row_field(row, "metadata_path", "") or "")
        pred_prob = parse_rate_decimal(get_row_field(row, "pred_prob", get_row_field(row, "win_rate", cfg["default_hit_prob"])), cfg["default_hit_prob"])
'''
    if "entry_vwap_premium_bps = as_float(get_row_field(row" not in txt:
        txt, _ = replace_once(txt, marker, insert, "optimizer extract usage fields")

    marker = '''            target_hit_bps=target_hit_bps, fail_loss_bps=fail_loss_bps, ev_bps=ev_bps,
            quality_weight=quality, tier=tier, tier_multiplier=tier_mult, vol_daily=vol_daily,
'''
    insert = '''            target_hit_bps=target_hit_bps, fail_loss_bps=fail_loss_bps,
            entry_policy=entry_policy, entry_vwap_premium_bps=entry_vwap_premium_bps,
            samples=samples, expected_return_col=expected_return_col, metadata_path=metadata_path,
            ev_bps=ev_bps,
            quality_weight=quality, tier=tier, tier_multiplier=tier_mult, vol_daily=vol_daily,
'''
    if "entry_policy=entry_policy" not in txt:
        txt, _ = replace_once(txt, marker, insert, "optimizer candidate construction fields")

    if txt != old_txt:
        path.write_text(txt, encoding="utf-8")
        print(f"[PATCHED] {path}")
    else:
        print(f"[UNCHANGED] {path}")


def main() -> int:
    patch_backtest()
    patch_adapter()
    patch_optimizer()
    print("[OK] portfolio bug fix patch applied")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
